-- Migration: Add idempotency support for news uploads
-- Date: 2025-11-28
-- Milestone: E.4 - Backend upload repository

-- Purpose:
--   Enable safe retries for news article uploads by preventing duplicate submissions.
--   Uses client-generated UUID as idempotency key.
--
-- Features:
--   1. idempotency_key column (UUID, nullable, unique)
--   2. Unique index with partial filter (only non-null keys)
--   3. RLS policy for user-created news
--   4. Storage bucket and policies for images
--
-- Usage:
--   Client generates UUID before upload, includes in request.
--   If retry occurs (network error, timeout), same UUID prevents duplicate.
--   Backend returns existing news_item_id if duplicate key detected.

-- ============================================================================
-- 1. Add idempotency_key column to news_items
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'news_items' 
    AND column_name = 'idempotency_key'
  ) THEN
    ALTER TABLE public.news_items
    ADD COLUMN idempotency_key UUID;
    
    RAISE NOTICE 'Added idempotency_key column to news_items';
  ELSE
    RAISE NOTICE 'idempotency_key column already exists, skipping';
  END IF;
END $$;

-- ============================================================================
-- 2. Create unique index on idempotency_key (partial index)
-- ============================================================================

-- Partial index: only indexes non-null values (allows null for existing rows)
CREATE UNIQUE INDEX IF NOT EXISTS idx_news_items_idempotency
ON public.news_items(idempotency_key)
WHERE idempotency_key IS NOT NULL;

COMMENT ON INDEX idx_news_items_idempotency IS 
'Unique index for idempotency keys. Prevents duplicate news uploads on retry.';

COMMENT ON COLUMN public.news_items.idempotency_key IS
'Client-generated UUID for preventing duplicate uploads on retry. 
Generated by client before upload attempt.';

-- ============================================================================
-- 3. RLS Policy: Users can create their own news
-- ============================================================================

-- Drop existing policy if it exists (for idempotent migration)
DROP POLICY IF EXISTS "Users can create own news" ON public.news_items;

-- Create policy: authenticated users can INSERT their own news
CREATE POLICY "Users can create own news"
ON public.news_items
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_profile_id);

COMMENT ON POLICY "Users can create own news" ON public.news_items IS
'Allows authenticated users to create news articles attributed to themselves.
Prevents users from creating news as other users (RLS enforcement).';

-- ============================================================================
-- 4. Optional: Add image_urls column if not exists
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'news_items' 
    AND column_name = 'image_urls'
  ) THEN
    ALTER TABLE public.news_items
    ADD COLUMN image_urls TEXT[];
    
    RAISE NOTICE 'Added image_urls column to news_items';
  ELSE
    RAISE NOTICE 'image_urls column already exists, skipping';
  END IF;
END $$;

COMMENT ON COLUMN public.news_items.image_urls IS
'Array of public URLs for news article images (uploaded to Supabase Storage).';

-- ============================================================================
-- 5. Storage Bucket: news-images (if not exists)
-- ============================================================================

-- Note: This requires Supabase Dashboard or Storage API
-- Cannot create buckets via SQL directly in standard Supabase setup
-- Instructions for admin:
--
-- 1. Go to Supabase Dashboard → Storage
-- 2. Create bucket: 'news-images'
-- 3. Set public: true (for public read access)
-- 4. File size limit: 5MB (recommended)
-- 5. Allowed MIME types: image/jpeg, image/png, image/webp
--
-- Or via Supabase Client:
-- await supabase.storage.createBucket('news-images', public: true);

-- ============================================================================
-- 6. Storage RLS Policies (requires bucket to exist)
-- ============================================================================

-- Policy 1: Users can upload images to their own folder
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'storage' 
    AND tablename = 'objects'
    AND policyname = 'Users can upload own news images'
  ) THEN
    EXECUTE 'CREATE POLICY "Users can upload own news images"
    ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (
      bucket_id = ''news-images'' 
      AND (storage.foldername(name))[1] = auth.uid()::text
    )';
    
    RAISE NOTICE 'Created storage policy: Users can upload own news images';
  ELSE
    RAISE NOTICE 'Storage policy already exists, skipping';
  END IF;
END $$;

-- Policy 2: Public read access to all images
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE schemaname = 'storage' 
    AND tablename = 'objects'
    AND policyname = 'Public read news images'
  ) THEN
    EXECUTE 'CREATE POLICY "Public read news images"
    ON storage.objects
    FOR SELECT
    TO public
    USING (bucket_id = ''news-images'')';
    
    RAISE NOTICE 'Created storage policy: Public read news images';
  ELSE
    RAISE NOTICE 'Storage policy already exists, skipping';
  END IF;
END $$;

-- ============================================================================
-- 7. Analyze table for query planner
-- ============================================================================

ANALYZE public.news_items;

-- ============================================================================
-- Testing queries
-- ============================================================================

-- Test 1: Insert news with idempotency key
-- INSERT INTO public.news_items (
--   news_item_id, title, content, category_id, user_profile_id, 
--   idempotency_key, image_urls, published_at
-- ) VALUES (
--   gen_random_uuid(),
--   'Test Article',
--   'Test content...',
--   '<category-uuid>',
--   '<user-uuid>',
--   gen_random_uuid(), -- Client generates this
--   ARRAY['https://example.com/image1.jpg'],
--   NOW()
-- );

-- Test 2: Duplicate idempotency key (should fail)
-- INSERT INTO public.news_items (
--   news_item_id, title, content, category_id, user_profile_id, 
--   idempotency_key, published_at
-- ) VALUES (
--   gen_random_uuid(),
--   'Duplicate Test',
--   'This should fail...',
--   '<category-uuid>',
--   '<user-uuid>',
--   '<same-uuid-as-test-1>', -- Duplicate key
--   NOW()
-- );
-- Expected: ERROR: duplicate key value violates unique constraint "idx_news_items_idempotency"

-- Test 3: Retrieve by idempotency key (for safe retry)
-- SELECT news_item_id, title 
-- FROM public.news_items 
-- WHERE idempotency_key = '<uuid>';

-- ============================================================================
-- Rollback script (if needed)
-- ============================================================================

-- To rollback this migration:
-- DROP POLICY IF EXISTS "Users can create own news" ON public.news_items;
-- DROP POLICY IF EXISTS "Users can upload own news images" ON storage.objects;
-- DROP POLICY IF EXISTS "Public read news images" ON storage.objects;
-- DROP INDEX IF EXISTS idx_news_items_idempotency;
-- ALTER TABLE public.news_items DROP COLUMN IF EXISTS idempotency_key;
-- ALTER TABLE public.news_items DROP COLUMN IF EXISTS image_urls;

-- ============================================================================
-- Performance notes
-- ============================================================================

-- 1. Partial index (WHERE idempotency_key IS NOT NULL) is efficient:
--    - Smaller index size (only indexes uploaded news)
--    - Allows null for existing/pre-migration rows
--    - Fast lookups for duplicate detection
--
-- 2. Image storage best practices:
--    - Compress images before upload (client-side with Isolate)
--    - Use WebP format for better compression (if supported)
--    - Generate thumbnails (200px) for list views
--    - Store original + compressed + thumbnail URLs
--
-- 3. RLS overhead:
--    - SECURITY DEFINER policies add minimal overhead
--    - Index on user_profile_id already exists (foreign key)
--    - auth.uid() function is optimized in Supabase
--
-- 4. Storage policies:
--    - Folder structure: {user_id}/{timestamp}_{filename}.jpg
--    - Public bucket = no auth check on read (fast CDN delivery)
--    - Write requires auth + folder ownership check

-- ============================================================================
-- End of migration
-- ============================================================================
