-- Engagement events to track started/completed for comments and ratings (non-destructive)
-- Allows computing BQ1 reliably without touching primary domain tables

BEGIN;

CREATE TABLE IF NOT EXISTS public.engagement_events (
  event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_profile_id integer REFERENCES public.user_profiles(user_profile_id) ON DELETE SET NULL,
  user_session_id integer REFERENCES public.user_sessions(user_session_id) ON DELETE SET NULL,
  news_item_id integer REFERENCES public.news_items(news_item_id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('comment','rating')),
  action text NOT NULL CHECK (action IN ('started','completed','canceled')),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_engagement_events_news ON public.engagement_events (news_item_id);
CREATE INDEX IF NOT EXISTS idx_engagement_events_user ON public.engagement_events (user_profile_id);
CREATE INDEX IF NOT EXISTS idx_engagement_events_session ON public.engagement_events (user_session_id);
CREATE INDEX IF NOT EXISTS idx_engagement_events_type_action ON public.engagement_events (event_type, action);
CREATE INDEX IF NOT EXISTS idx_engagement_events_created_at ON public.engagement_events (created_at);

COMMIT;

-- RLS (optional): enable and allow users to insert their own events
-- ALTER TABLE public.engagement_events ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "insert_own_events" ON public.engagement_events FOR INSERT TO public
--   WITH CHECK (auth.uid() = (SELECT user_auth_id FROM public.user_profiles up WHERE up.user_profile_id = user_profile_id));